### PR TITLE
Big refactoring to node implementation

### PR DESCRIPTION
**Pull request by dario-rodriguez**
The application is deployed at http://de-mucdevondepl01:8091
To read the emails sended by the application you can go to http://de-mucdevondepl01:8092

IMPORTANT: The application is working but there is something peding:

* Test: all test are missing
* JSDoc: all classes/methods do not have a proper JSDoc.
* Better exception handling: layer service shouldn't know anything about the HTTP response to the client. Thats why we throw a normal Error in the service layer and then we catch them at controller layer and send to the client the proper HTTP error. This mechanism is OK, but we can improve it by creating errors and then adding an error handling which is the responsible to send the correct HTTP error to the client. This feature will arrive soon.

### CODE REVIEW

**Comment by sjimenez77** [comment]
Hi @dario-rodriguez, should we merge this now or wait until pending features?

**Comment by sjimenez77** [comment]
Just checked the deployed version and the bookings are not shown in the waiter private area. Please check it. Thanks!

**Comment by dario-rodriguez** [comment]
Hello Santos, 
I solved the error in the private area and redeployed the application.
If you want to merge now for me is ok. I will create a new PR when everything are done.

Kind regards

**Comment by sjimenez77** [comment]
Hi @dario-rodriguez,

Thanks for the fix, but I have found another one 🙃... Sorting in the waiter area  is not working in bookings nor orders.

Please check it **when you come back from holidays**!

Kind regards

**Comment by dario-rodriguez** [comment]
Hello @sjimenez77 ,

PR updated and application redeployed.

**Comment by sjimenez77** [comment]
Hi @dario-rodriguez, everything seems to work fine now. Merging!

Thanks!

**Pull request merged**
