### PR TITLE
APP_INITIALIZER sample for Angular

### PR DESCRIPTION
**Pull request by amarinso**
This code is a sample for using APP_INITIALIZER in Angular to load external configuration before the app initializes as referenced on issue #146 

The behavior is configurable by setting `config.loadExternalConfig = true/false` so you can skip the http request to the `/config` endpoint.

If enabled, the app will wait to fetch a JSON file on the /config endpoint and will merge its contents on the config object, overwriting any existing property.

The `/config` endpoint is redirected on development using the local proxy configuration to fetch `src/external-config.json` file (as per configured on angular.json file)

The result of the config fetched is shown on the application footer, here by default it shows 1.0.0-external (it may be better to change this). This is somehow hacky as it is monkey patching the config object (supposedly a const, but since it is an object, it's properties can change). It will be better if we create a global configService as proposed in  #159 merging from several variable sources.

When deploying the application to a container there are several options:
- Overwrite the external-config.json file on container init with proper contents
- Reverse proxy the /config endpoint to another server (like Spring Cloud Config)

### CODE REVIEW

**Comment by sjimenez77** [comment]
Thanks @amarinso for this contribution! 
Please, sign in the CLA in order to be able to approve your PR.

**Comment by sjimenez77** [comment]
No, you don't have to do anything then, it is a CLA assistant issue. Please, click tomorrow again in the _recheck_ link because it is a rare but known problem. For some strange reason, some people that already have signed the CLA got this message but after clicking in the link some time later the system accepted it.

**Comment by amarinso** [comment]
Reasons for not using environment from this article:
[https://christianlydemann.com/implementing-dynamic-environments-in-angular-for-avoiding-one-build-per-environment/](https://christianlydemann.com/implementing-dynamic-environments-in-angular-for-avoiding-one-build-per-environment/)

The reason why you don’t want to create a separate build for every environment is:

1. It slows down CI pipelines because it needs to create a build for every environment
2. It increases the risk of errors/differences in different environments because the builds are separate
3. It adds unnecessary information about other environments in the code
4. You might, for security reasons, don’t want to show confidential information in the environment config, which is saved to the version control

**Comment by amarinso** [comment]
This new commit introduces the configService for the Angular application.

- All  configuration for application should now be managed through `configService`.
- The only exception is for the `environment.production` variable on the environment options that can change behavior before the external configuration is loaded.
- This means that config.ts can not be directly referenced and values should be obtained by injecting the service and using `configService.getValues()`

`config.ts` is moved to `app/core/config/config.ts` next to the rest of the service files

`config.ts` still defines the default values for all configuration.

`config.ts/loadExternalConfig=true/false` indicates that external configuration must be fetched on app initialization

`external-config.json` is provided as sample for development, it is served by the development proxy

`docker-external-config.json` is provided as sample for docker usage. Also `nginx.conf` is modified to redirect `/config` path to resolve this file.

If external configuration is enabled, values fetched from `/config` will override those on the original `config.ts` file.

Content from all environment.*.ts files now is reduced to the value of the `production` property. In each case, the particular configuration should be provided via the loadExternalConfig mechanism for the specifics of the runtime. This means no more propietary urls are left on the application files.

BackendType removed as no occurences where found through the code.

**Comment by amarinso** [comment]
> No, you don't have to do anything then, it is a CLA assistant issue. Please, click tomorrow again in the _recheck_ link because it is a rare but known problem. For some strange reason, some people that already have signed the CLA got this message but after clicking in the link some time later the system accepted it.

It seems that my local configuration for `user.email` was not this account but other, so CLA required *both* users to sign the agreement to proceed.

Now I've solved it and I hope PRs can move forward

**Comment by sjimenez77** [comment]
I think that we can leverage these changes so we could remove the following: 
- all the `enviroment.*.ts` files but the `prod` one, 
- the related sections in the `angular.json` and 
- the related scripts in the `package.json` file as they all have the same content

In such way we would reduce the complexity and remove some unnecessary content. Does it make sense?

**Comment by amarinso** [comment]
> reduce the complexity and remove some unnecessary content

always makes sense :-)

mind you, this other environments should be updated in order to provide the application the necessary external configuration to work properly, on my PR I've only updated the docker related files.

**Comment by sjimenez77** [comment]
I have solved the conflicts and the linting errors found before merging: 

```
ERROR: C:/Projects/my-thai-star/angular/src/app/app.component.ts[22, 1]: trailing whitespace
ERROR: C:/Projects/my-thai-star/angular/src/app/cockpit-area/reservation-cockpit/reservation-cockpit.component.ts[50, 6]: trailing whitespace
ERROR: C:/Projects/my-thai-star/angular/src/app/core/authentication/auth.service.ts[13, 37]: missing whitespace
ERROR: C:/Projects/my-thai-star/angular/src/app/core/authentication/auth.service.ts[13, 51]: missing whitespace
ERROR: C:/Projects/my-thai-star/angular/src/app/core/config/config.module.ts[2, 34]: " should be '
ERROR: C:/Projects/my-thai-star/angular/src/app/core/config/config.service.ts[15, 5]: comment must start with a space
ERROR: C:/Projects/my-thai-star/angular/src/app/core/config/config.service.ts[30, 16]: " should be '
ERROR: C:/Projects/my-thai-star/angular/src/app/core/config/config.service.ts[30, 47]: Missing semicolon
ERROR: C:/Projects/my-thai-star/angular/src/app/core/config/config.ts[18, 18]: Properties should be separated by semicolons
ERROR: C:/Projects/my-thai-star/angular/src/app/core/config/config.ts[19, 27]: Properties should be separated by semicolons
ERROR: C:/Projects/my-thai-star/angular/src/app/core/config/config.ts[20, 23]: Properties should be separated by semicolons
ERROR: C:/Projects/my-thai-star/angular/src/app/core/config/config.ts[21, 26]: Properties should be separated by semicolons
ERROR: C:/Projects/my-thai-star/angular/src/app/core/config/config.ts[22, 30]: Properties should be separated by semicolons
ERROR: C:/Projects/my-thai-star/angular/src/app/core/config/config.ts[34, 32]: comment must start with a space
```

We have to be careful with linting errors mostly for CI pipelines.

**Pull request merged**
