### PR TITLE
Add prediction use case for SAP HANA

### PR DESCRIPTION
**Pull request by breglerj**
- Add manager role and user
- Add prediction cockpit and service

### CODE REVIEW

**Comment by sjimenez77** [comment]
In order to be able to merge this PR we need to fix first the Travis CI build. The errors Travis CI reports are related with the failing tests for `PredictionCockpitComponent` and `PredictionService` Angular classes. 

Besides, as My Thai Star works with different databases and has different backend implementations, we **must** add a toggle feature to be able to enable or disable SAP HANA integration and features at backend and frontend. 

At frontend I suggest to use the latest config object at `angular\src\app\core\config\config.ts` and add the necessary properties to load or not the SAP HANA frontend features.

**Comment by Rohit90700** [comment]
We have tried tested MTSJ Backend and below are our findings :
 
Currently the Travis is failing because,junits are not updated as per code changes in this PR.
 
Given below test cases are failing:
 
DishmanagementTest.filterDishes 
DishmanagementTest.findAllDishes 
ImagemanagementTest.findImageById 
OrdermanagementTest.orderAnOrder 
OrdermanagementTest.orderAnOrderAlreadyCreated
OrdermanagementTest.orderAnOrderBookingNotExist 
OrdermanagementTest.orderAnOrderInviteNotExist
OrdermanagementTest.orderAnOrderWithWrongToken 
 

Exception in logs :
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Invocation of init method failed; nested exception is javax.persistence.PersistenceException: [PersistenceUnit: default] Unable to build Hibernate SessionFactory; nested exception is org.hibernate.tool.schema.spi.SchemaManagementException: Schema-validation: missing table [OrderedDishesPerDay]
 

Please also update new test-cases for the prediction use case that has been written.

**Comment by breglerj** [comment]
> 
> 
> In order to be able to merge this PR we need to fix first the Travis CI build. The errors Travis CI reports are related with:
> 
>     * The failing tests for `PredictionCockpitComponent` and `PredictionService` Angular classes.
> 
>     * Error building mtsj-core.
> 
> 
> Besides, as My Thai Star works with different databases and has different backend implementations, we **must** add a toggle feature to be able to enable or disable SAP HANA integration and features at backend and frontend.
> 
> At frontend I suggest to use the latest config object at `angular\src\app\core\config\config.ts` and add the necessary properties to load or not the SAP HANA frontend features.

I've pushed a new change that fixes the build. At least for me locally, that is. I don't know why the Travis build fails with an error in `ReservationDialogComponent`. I don't think this is related to my change. Let me know if you think it is related to this PR.

I've added a new configuration option `enablePrediction`. If set to `false` trying to access the prediction UI will result in a "Feature not supported" message. I've added a new component for this.

**Comment by breglerj** [comment]
> 
> 
> We have tried tested MTSJ Backend and below are our findings :
> 
> Currently the Travis is failing because,junits are not updated as per code changes in this PR.
> 
> Given below test cases are failing:
> 
> DishmanagementTest.filterDishes
> DishmanagementTest.findAllDishes
> ImagemanagementTest.findImageById
> OrdermanagementTest.orderAnOrder
> OrdermanagementTest.orderAnOrderAlreadyCreated
> OrdermanagementTest.orderAnOrderBookingNotExist
> OrdermanagementTest.orderAnOrderInviteNotExist
> OrdermanagementTest.orderAnOrderWithWrongToken
> 
> Exception in logs :
> org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Invocation of init method failed; nested exception is javax.persistence.PersistenceException: [PersistenceUnit: default] Unable to build Hibernate SessionFactory; nested exception is org.hibernate.tool.schema.spi.SchemaManagementException: Schema-validation: missing table [OrderedDishesPerDay]
> 
> Please also update new test-cases for the prediction use case that has been written.

The tests pass now. I've also added a test case for the prediction management.

**Comment by vapadwal** [comment]
Closing this PR as we have already merged the PR related to SAP hana
https://github.com/devonfw/my-thai-star/pull/205

**Pull request closed without merging**
