### PR TITLE
removed covalent from angular app

### PR DESCRIPTION
**Pull request by suprishi**

### CODE REVIEW

**Comment by jambulud** [comment]
I have been checking this PR and I found that inline styles are being used in multiple places. ¿Could you use css classes intead?
If you are trying to simulate some covalent classes with inline styles you can create a new stylesheet and include this new file in the styles array inside angular.json

**Comment by suprishi** [comment]
> I have been checking this PR and I found that inline styles are being used in multiple places. ¿Could you use css classes intead?
> If you are trying to simulate some covalent classes with inline styles you can create a new stylesheet and include this new file in the styles array inside angular.json

I removed all the inline styles I had added and put them in their respective component stylesheets. Hope it is cleaner now. Thanks.

**Comment by sjimenez77** [comment]
Hi @suprishi, there is a conflict in this pull request. 
Please, fix this in order to merge it. Thanks!

**Comment by suprishi** [comment]
> Hi @suprishi, there is a conflict in this pull request.
> Please, fix this in order to merge it. Thanks!

Hi @sjimenez77, resolved the conflict. Thanks.

**Comment by sjimenez77** [comment]
Hi @suprishi, Travis CI is failing because of the CommentAlertComponent test is failing:

image

Please fix this test in order to merge this PR.

Thanks!

**Comment by sjimenez77** [comment]
Hi @suprishi,

Please, replace the the contents of the `src\app\sidenav\comment-alert\comment-alert.component.spec.ts` file with the following code in order to fix the test:

```TypeScript
import { async, ComponentFixture, TestBed } from '@angular/core/testing';
import {
  MatButtonModule,
  MatDialogModule,
  MAT_DIALOG_DATA,
} from '@angular/material';
import { CommentAlertComponent } from './comment-alert.component';

describe('CommentAlertComponent', () => {
  let component: CommentAlertComponent;
  let fixture: ComponentFixture<CommentAlertComponent>;

  beforeEach(async(() => {
    TestBed.configureTestingModule({
      declarations: [CommentAlertComponent],
      imports: [MatButtonModule, MatDialogModule],
      providers: [
        {
          provide: MAT_DIALOG_DATA,
          useValue: {},
        },
      ],
    }).compileComponents();
  }));

  beforeEach(() => {
    fixture = TestBed.createComponent(CommentAlertComponent);
    component = fixture.componentInstance;
    fixture.detectChanges();
  });

  it('should create', () => {
    expect(component).toBeTruthy();
  });
});
```

Thanks!

**Comment by suprishi** [comment]
> Hi @suprishi,
> 
> Please, replace the the contents of the `src\app\sidenav\comment-alert\comment-alert.component.spec.ts` file with the following code in order to fix the failing test:
> 
> ```ts
> import { async, ComponentFixture, TestBed } from '@angular/core/testing';
> import {
>   MatButtonModule,
>   MatDialogModule,
>   MAT_DIALOG_DATA,
> } from '@angular/material';
> import { CommentAlertComponent } from './comment-alert.component';
> 
> describe('CommentAlertComponent', () => {
>   let component: CommentAlertComponent;
>   let fixture: ComponentFixture<CommentAlertComponent>;
> 
>   beforeEach(async(() => {
>     TestBed.configureTestingModule({
>       declarations: [CommentAlertComponent],
>       imports: [MatButtonModule, MatDialogModule],
>       providers: [
>         {
>           provide: MAT_DIALOG_DATA,
>           useValue: {},
>         },
>       ],
>     }).compileComponents();
>   }));
> 
>   beforeEach(() => {
>     fixture = TestBed.createComponent(CommentAlertComponent);
>     component = fixture.componentInstance;
>     fixture.detectChanges();
>   });
> 
>   it('should create', () => {
>     expect(component).toBeTruthy();
>   });
> });
> ```
> 
> Thanks!

Hi @sjimenez77, made the corrections. Thanks.

**Pull request merged**
