### PR TITLE
#DEVC-254-update version

### PR DESCRIPTION
**Pull request by amitcdubey**
Updated Angular version

### CODE REVIEW

**Comment by amitcdubey** [comment]
i have updated the following dependencies 
Angular 
Covalent
Angular Material
etc ..

Kindly review this.

**Comment by sjimenez77** [comment]
Hi @amitcdubey,

Please modify the `devDependencies` section in the `package.json` to match the following ones:

```json
"devDependencies": {
    "@angular-devkit/build-angular": "~0.13.0",
    "@angular/cli": "~7.3.6",
    "@angular/compiler-cli": "~7.2.0",
    "@angular/language-service": "~7.2.0",
    "@types/node": "~8.9.4",
    "@types/jasmine": "~2.8.8",
    "@types/jasminewd2": "~2.0.3",
    "codelyzer": "~4.5.0",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.11.0",
    "typescript": "~3.2.2"
  }
```

These are the ones generated for a new project with **the latest Angular CLI**. 

I suggest you, when you have to do this kind of tasks, to update locally the Angular CLI and generate a sample project to check the generated `package.json` file.

**Comment by amitcdubey** [comment]
Hi am getting below error 

Chrome 72.0.3626 (Windows 10.0.0) ERROR
  {
    "message": "An error was thrown in afterAll\nUncaught TypeError: env.catchExceptions is not a function",
    "str": "An error was thrown in afterAll\nUncaught TypeError: env.catchExceptions is not a function"
  }
Chrome 72.0.3626 (Windows 10.0.0): Executed 52 of 52 ERROR (0 secs / 43.131 secs)
Chrome 72.0.3626 (Windows 10.0.0) ERROR
  {
    "message": "An error was thrown in afterAll\nUncaught TypeError: env.catchExceptions is not a function",
    "str": "An error was thrown in afterAll\nUncaught TypeError: env.catchExceptions is not a function"
}

**Comment by sjimenez77** [comment]
Hi @amitcdubey,

I have been reviewing this, and at a glance I have realized that some dependencies are not matching with the ones that you can see when you start a new project as I told you some days ago:

```
"karma-cli": "~1.0.1",
"karma-coverage-istanbul-reporter": "~1.4.2",
"karma-jasmine": "~1.1.2",
```

Changing these dependencies the error is gone. Anyway, please copy and paste the following dependencies to your `package.json`, install dependencies and commit and push the changes to close the PR:

```
"dependencies": {
    "@angular/animations": "~7.2.0",
    "@angular/cdk": "~7.3.6",
    "@angular/common": "~7.2.0",
    "@angular/compiler": "~7.2.0",
    "@angular/core": "~7.2.0",
    "@angular/forms": "~7.2.0",
    "@angular/http": "~7.2.0",
    "@angular/material": "~7.3.6",
    "@angular/platform-browser": "~7.2.0",
    "@angular/platform-browser-dynamic": "~7.2.0",
    "@angular/platform-server": "~7.2.0",
    "@angular/pwa": "^0.13.6",
    "@angular/router": "~7.2.0",
    "@angular/service-worker": "~7.2.0",
    "@covalent/core": "2.0.1",
    "@covalent/dynamic-forms": "2.0.1",
    "@covalent/highlight": "2.0.1",
    "@covalent/http": "2.0.1",
    "@covalent/markdown": "2.0.1",
    "@ngx-translate/core": "11.0.1",
    "@ngx-translate/http-loader": "4.0.0",
    "core-js": "^2.5.3",
    "flag-icon-css": "^3.3.0",
    "hammerjs": "^2.0.8",
    "highlight.js": "^9.15.6",
    "intl": "^1.2.5",
    "lodash": "^4.17.11",
    "moment": "^2.24.0",
    "ng-pick-datetime": "7.0.0",
    "ng-pick-datetime-moment": "1.0.8",
    "ngx-moment": "3.4.0",
    "rxjs": "^6.3.3",
    "rxjs-compat": "^6.3.3",
    "showdown": "^1.9.0",
    "web-animations-js": "^2.3.1",
    "whatwg-fetch": "^3.0.0",
    "zone.js": "^0.8.29"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.13.0",
    "@angular-devkit/schematics": "~7.3.6",
    "@angular/cli": "~7.3.6",
    "@angular/compiler-cli": "~7.2.0",
    "@angular/language-service": "~7.2.0",
    "@types/hammerjs": "2.0.36",
    "@types/jasmine": "~2.8.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/lodash": "^4.14.123",
    "@types/node": "~8.9.4",
    "@types/selenium-webdriver": "3.0.15",
    "codelyzer": "~4.5.0",
    "electron": "4.1.0",
    "electron-builder": "20.28.1",
    "electron-reload": "1.4.0",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "~1.4.2",
    "karma-firefox-launcher": "^1.1.0",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "npm-run-all": "4.1.5",
    "npx": "10.2.0",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.11.0",
    "typescript": "~3.2.2",
    "wait-on": "3.2.0",
    "webdriver-manager": "12.1.1"
  },
```

Regards,
Santos

**Pull request merged**
