### PR TITLE
Changed traefik version from 2.0.0 to 2.0

### PR DESCRIPTION
**Pull request by dario-rodriguez**
In this PR I changed the traefik version inside the docker-compose.yml from 2.0.0 to 2.0 as described by @markusschuh in the issue #280 

@markusschuh can you check if this is correct and then we can close those issue?

### CODE REVIEW

**Comment by markusschuh** [comment]
Perfect. "2,0" is a good choice. Compare with chapter "Supported tags and respective Dockerfile links" on https://hub.docker.com/_/traefik

It may be, the the traefik team will also publish a "2.0-alpine" tag some time (as for 1.7-alpine).  But that is the future.

**Comment by dario-rodriguez** [comment]
I think that traefik docker base image is "scratch", so in this specific case: which benefits adds the extra layers of alpine?

**Comment by dario-rodriguez** [comment]
Anyway, I will close this PR and also de related issue, but we can continue the discussion in the teams channel or yammer.

**Comment by markusschuh** [comment]
For a demo setup like here, the alpine is a bit more convenient than scratch, since debugging is a bit easier. (`docker exec -it $imageid sh`) Anyway I have missed, that traefik since v2.0.0 now has [switched to alpine](https://github.com/containous/traefik/issues/5453) as default - so my remark was useless.

**Pull request merged**
