### PR TITLE
Angular migration

### PR DESCRIPTION
**Pull request by dattuchillal**
Hi @sjimenez77, I have updated the "My Thai star" application to Angular 9 and also updated the Transloco module. In Angular 9, Hammer Js is removed so I have updated the script section in Angular JSON. And I have tested in my local.

Please review it and let me know.

### CODE REVIEW

**Comment by sjimenez77** [comment]
Hi @chdattat, you **must sign** the CLA agreement once to be able to contribute in devonfw repositories. It seems that you have two different accounts and you committed changes with @chdattat instead of @dattuchillal.

**Comment by sjimenez77** [comment]
Hi @dattuchillal, I have found a few issues:

1. My Thai Star detects your local language when you start the application, but it is not properly selected in the header button. For example. The flag should be the Spanish one for me and not the one from the UK:
image

2. The column labels on the admin area dissapeared:
image

3. Labels from alerts are not translated:
image

**Comment by dattuchillal** [comment]
> Hi @dattuchillal, I have found a few issues:
> 
> 1. My Thai Star detects your local language when you start the application, but it is not properly selected in the header button. For example. The flag should be the Spanish one for me and not the one from the UK:
>    image
> 2. The column labels on the admin area dissapeared:
>    image
> 3. Labels from alerts are not translated:
>    image

Hi @sjimenez77 ,
I have committed the changes, can you check it. In cases any issue, please let me know

**Comment by sjimenez77** [comment]
Hi @dattuchillal, the flag error is still pending. The 2. and 3. are now ok.

**Comment by dattuchillal** [comment]
> Hi @dattuchillal, the flag error is still pending. The 2. and 3. are now ok.

Hi @sjimenez77,

It's working now. I have tested and committed the changes for the flag error. Please check it from your side and let me now.

**Comment by sjimenez77** [comment]
Hi @dattuchillal, 

It is mandatory to **sign the CLA** with all the users that have made contributions in this PR in order to merge it. Once you signed you will not be required to do it again. 

Besides, **Travis CI** is failing because of tests are not passing. So, please fix them. See https://travis-ci.com/github/devonfw/my-thai-star/jobs/333075904

image

Thanks!

**Comment by dattuchillal** [comment]
> Hi @dattuchillal,
> 
> Everything seems to be fine now. But...
> 
> It is mandatory to **sign the CLA** with all the users that have made contributions in this PR in order to merge it. Once you signed you will not be required to do it again.
> 
> Besides, **Travis CI** is failing because of tests are not passing. So, please fix them. See https://travis-ci.com/github/devonfw/my-thai-star/jobs/333075904
> 
> image
> 
> Thanks!

Hi @sjimenez77 ,
Can I know which command are you using to run the test cases? Because I am unable to run the test cases. I tried npm test/ng test --browsers Chrome but in the middle, it stops. Sharing the screenshot below.

**And getting messages like :**
14 05 2020 16:42:35.981:WARN [launcher]: Chrome have not captured in 60000 ms, killing.
14 05 2020 16:42:39.192:WARN [launcher]: Chrome was not killed in 2000 ms, sending SIGKILL.
14 05 2020 16:42:41.308:WARN [launcher]: Chrome was not killed by SIGKILL in 2000 ms, continuing.                  46380979
14 05 2020 16:42:51.783:WARN [karma]: No captured browser, open http://localhost:9876/
14 05 2020 16:43:10.170:INFO [launcher]: Trying to start Chrome again (2/2).

image

**Comment by dattuchillal** [comment]
> > Hi @dattuchillal,
> > Everything seems to be fine now. But...
> > It is mandatory to **sign the CLA** with all the users that have made contributions in this PR in order to merge it. Once you signed you will not be required to do it again.
> > Besides, **Travis CI** is failing because of tests are not passing. So, please fix them. See https://travis-ci.com/github/devonfw/my-thai-star/jobs/333075904
> > image
> > Thanks!
> 
> Hi @sjimenez77 ,
> Can I know which command are you using to run the test cases? Because I am unable to run the test cases. I tried npm test/ng test --browsers Chrome but in the middle, it stops. Sharing the screenshot below.
> 
> **And getting messages like :**
> 14 05 2020 16:42:35.981:WARN [launcher]: Chrome have not captured in 60000 ms, killing.
> 14 05 2020 16:42:39.192:WARN [launcher]: Chrome was not killed in 2000 ms, sending SIGKILL.
> 14 05 2020 16:42:41.308:WARN [launcher]: Chrome was not killed by SIGKILL in 2000 ms, continuing. 46380979
> 14 05 2020 16:42:51.783:WARN [karma]: No captured browser, open http://localhost:9876/
> 14 05 2020 16:43:10.170:INFO [launcher]: Trying to start Chrome again (2/2).
> 
> image

Hi @sjimenez77,

Now updated test cases.  I ran the test cases with different karma config. Now built is passes. Below is the screenshot.

I will check **sign the CLA**, how to do it.

image

**Comment by chdattat** [comment]
Hi @sjimenez77,
Now CLA  submission has done. Please check it and let me know in case any issue

**Pull request merged**
