### PR TITLE
Changes in order to deploy on OpenShift

### PR DESCRIPTION
**Pull request by mickume**
Here are my changes to the reference application in order to deploy the java backend and angular front-end on the Red Hat OpenShift Container Platform.

### CODE REVIEW

**Comment by cbeldacap** [comment]
Hi Michael,

I've seen that the OpenShift build uses an `environment` that needs to have `http://localhost:8081` URL setup. Instead of changing the `environment.prod.ts` file, I've changed the `assemble` file of s2i-angular so that the used environment is the dev one, because it will always point to this local URL:

https://github.com/cbeldacap/s2i/blob/master/s2i/angular/bin/assemble#L23 (yet to be PR-ed)

I think it maybe fits better with everyone's needs. Does it make sense?

**Comment by mickuehl** [comment]
Hi Cristobal,

I might miss something but I think it will break the setup. There are three artefacts that depend on each other:

(1) environments.prod.ts or environment.ts
in https://github.com/oasp/my-thai-star/tree/develop/angular/src/environments

(2) https://github.com/oasp/s2i/blob/master/s2i/angular/bin/assemble
(3) https://github.com/oasp/s2i/blob/master/templates/mythaistar/oasp-mythaistar-angular-template.json

(3) is the template that defines the build and deployment of the angular parts of the app, i.e. this is where the chain of dependencies starts. There is a env variable in the template $BUILD_TARGET (ca. line 121) that defaults to 'prod' but could be used to change to build for a different environment.

$BUILD_TARGET is used in (2) to tell the assemble script which environment config file to select and modify, i.e. looking for $REST_ENDPOINT_PATTERN, replacing it with $REST_ENDPOINT_URL. Both are also defined in (3).

```shell
TARGET_ENV_FILE="src/environments/environment.$BUILD_TARGET.ts"
sed -i "s|$REST_ENDPOINT_PATTERN|$REST_ENDPOINT_URL|" $TARGET_ENV_FILE
```

With this said, I do not know how the behaviour of yarn changes with the change. The reason I'm raising this is that e.g. in RAILS, there is different behaviour when you start the app with an environment variable RAILS_ENV='DEV' vs. 'PROD'. Example: in DEV, the runtime does code-reloading and does not optimise assets e.g. does not compress js/css files whereas in PROD it is the opposite. No idea if similar stuff happens in yarn, depending of the environment.

Nevertheless, for your change to work, you have change line 

```shell
TARGET_ENV_FILE=
```

also, otherwise the script patches an environment file that yarn ignores ...

**Comment by cbeldacap** [comment]
Hi @mickuehl ,

I've started fixing some "collateral" Jenkinsfiles to merge your PR in the application.

**Comment by cbeldacap** [comment]
@mickuehl 

I'm adding this PR's changes plus some others related with DevOps (deployment, usage in CICD environments, etc.) in #53 .

I'll proceed to close this when after the testing period.

**Comment by cbeldacap** [comment]
As the **devonfw-angular** base image for OpenShift lets the user specify the string that is going to be substituted, is this PR still needed?  @mickuehl 

image

**Pull request closed without merging**
